

// src/auth-worker.js
import puppeteer from "@cloudflare/puppeteer";

/**
 * 1. GET COOKIE (The Automation)
 * Uses a headless browser to visit the site and grab the cookies.
 */
async function getLatestCookieFromTarget(env) {
    console.log('[AuthWorker] 🤖 Launching Headless Browser to find new cookie...');
    let browser = null;

    try {
        // Launch Cloudflare's Browser
        // NOTE: Ensure you added [browser] binding in wrangler.toml named "MYBROWSER"
        browser = await puppeteer.launch(env.MYBROWSER);
        const page = await browser.newPage();

        // mimic a standard desktop screen
        await page.setViewport({ width: 1920, height: 1080 });

        // Go to BC Game Crash
        console.log('[AuthWorker] Compass set to BC Game...');
        // We go to the game page specifically as it often triggers the necessary session cookies
        await page.goto('https://bc.fun/game/crash', { 
          waitUntil: 'domcontentloaded', // Changed from networkidle0 to be faster
          timeout: 45000 // Give it a bit more time
      });
      await new Promise(r => setTimeout(r, 3000));

        // Grab all cookies generated by the visit
        const cookies = await page.cookies();
        
        // Convert to the string format BC Game expects: "key=value; key2=value2;"
        const cookieString = cookies.map(c => `${c.name}=${c.value}`).join('; ');

        console.log(`[AuthWorker] 🍪 Extraction complete. Found ${cookies.length} cookies.`);
        return cookieString;

    } catch (e) {
        console.error('[AuthWorker] 💥 Browser Automation Failed:', e.message);
        return null; 
    } finally {
        if (browser) await browser.close(); 
    }
}

/**
 * 2. VALIDATE COOKIE (The Health Check)
 * Uses YOUR PROVEN HEADERS to see if the new cookie actually works.
 */
async function validateCookie(cookie) {
    if (!cookie) return false;
    
    console.log('[AuthWorker] 🏥 Running Health Check on new cookie...');
    
    // We try to fetch just 1 round of history to see if the API accepts us.
    // URL from your crash-oracle-do.js
    const API_URL = 'https://bc.fun/api/game/bet/multi/history';
    
    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            // --- HEADERS COPIED FROM YOUR crash-oracle-do.js ---
            headers: {
                'Content-Type': 'application/json',
                'Origin': 'https://bc.fun',
                'Referer': 'https://bc.fun/', 
                // Matches the user agent we used in Puppeteer
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
                'Cookie': cookie, // Testing the NEW cookie
            },
            body: JSON.stringify({
                gameUrl: 'crash',
                page: 1,
                pageSize: 1 // We only need 1 item to prove it works
            }),
        });

        if (response.ok) {
            console.log('[AuthWorker] ✅ Health Check PASSED. Cookie is valid.');
            return true;
        } else {
            console.warn(`[AuthWorker] ⚠️ Health Check FAILED. API Status: ${response.status}`);
            return false;
        }
    } catch (err) {
        console.error('[AuthWorker] ❌ Health Check Error:', err.message);
        return false;
    }
}

/**
 * 3. MAIN SCHEDULER
 */
export default {
  async scheduled(event, env, ctx) {
    console.log('[AuthWorker] ⏰ Scheduled Auto-Update started.');

    // Step A: get the cookie (Automation)
    const newCookie = await getLatestCookieFromTarget(env);

    // Step B: validate the cookie (Safety Net)
    const isValid = await validateCookie(newCookie);

    // Step C: If valid, send to the Oracle DO
    if (isValid) {
      const id = env.CRASH_ORACLE_DO.idFromName("GLOBAL");
      const stub = env.CRASH_ORACLE_DO.get(id);

      const response = await stub.fetch("https://dummy-url/internal/update-auth", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ cookie: newCookie }), 
      });

      if (response.ok) {
        console.log('[AuthWorker] 🚀 SUCCESS: System updated with fresh credentials.');
      } else {
        console.error(`[AuthWorker] ❌ DO rejected update: ${response.status}`);
      }
    } else {
      console.log('[AuthWorker] 🛡️ Update blocked by Health Check. The system will continue using the old working cookie.');
    }
  },
};